// reflectionWriterCron — Timer Trigger (daily @ 15:30 UTC)
//
// Guarantees the 3-day reflection cadence. Reads runtimeMemory.reflectionDigest,
// finds agents flagged reflectionOverdue, and writes each a grounded
// type='reflection' memory (source:'auto:reflection'). Reflection text is
// generated by the heartbeat's existing gemini-pro path (callGeminiProposal),
// with a deterministic template fallback so a bad/empty LLM response never leaves
// an agent overdue. Standalone — no changes to the heartbeat engine.

const storage = require('../_utils/companyStorage');
const gemini = require('../companyHeartbeat/gemini');
const demoGuard = require('../_utils/demoGuard');
const R = require('./reflectionWriter');

module.exports = async function (context) {
  if (demoGuard.timerSkip(context)) return;
  context.log('[reflectionWriterCron] start');

  let rt;
  try {
    rt = (await storage.getState('runtimeMemory')) || {};
  } catch (err) {
    context.log.error('[reflectionWriterCron] failed to load runtimeMemory:', (err && err.message) || err);
    return;
  }

  const digest = rt.reflectionDigest;
  if (!digest || !digest.perAgent) {
    context.log('[reflectionWriterCron] no reflectionDigest present — exiting');
    return;
  }

  const overdue = R.selectOverdueAgents(digest);
  if (overdue.length === 0) {
    context.log('[reflectionWriterCron] no overdue agents — nothing to do');
    return;
  }

  let memories;
  try {
    memories = (await storage.getState('agentMemories')) || {};
  } catch (err) {
    context.log.error('[reflectionWriterCron] failed to load agentMemories:', (err && err.message) || err);
    return;
  }

  let modelKey = null;
  try { modelKey = (await gemini.getActiveModel()).key; } catch (e) { modelKey = null; }

  const now = Date.now();
  let written = 0;
  const writtenAgents = [];

  for (let i = 0; i < overdue.length; i++) {
    const agentId = overdue[i].agentId;
    const data = overdue[i].data;
    const list = Array.isArray(memories[agentId]) ? memories[agentId] : [];

    if (R.hasRecentReflection(list, now, R.SKIP_HOURS)) {
      context.log('[reflectionWriterCron]', agentId, 'reflected within', R.SKIP_HOURS, 'h — skipping');
      continue;
    }

    let text = null;
    try {
      text = await gemini.callGeminiProposal(R.buildReflectionPrompt(agentId, data));
    } catch (e) {
      context.log.warn('[reflectionWriterCron]', agentId, 'LLM call failed:', (e && e.message) || e);
    }
    if (!text || !String(text).trim()) {
      text = R.buildTemplateFallback(agentId, data);
      context.log('[reflectionWriterCron]', agentId, 'used template fallback');
    }

    const mem = R.makeReflectionMemory({ text: text, now: now, model: modelKey });
    list.push(mem);
    memories[agentId] = R.capMemories(list, R.MAX_MEMORIES);
    written++;
    writtenAgents.push(agentId);
  }

  if (written > 0) {
    try {
      await storage.setState('agentMemories', memories);
      context.log('[reflectionWriterCron] wrote', written, 'reflections for:', writtenAgents.join(', '));
    } catch (err) {
      context.log.error('[reflectionWriterCron] failed to save agentMemories:', (err && err.message) || err);
    }
  } else {
    context.log('[reflectionWriterCron] complete — 0 reflections written');
  }
};
