// pixel-agent-share-card — Generates a branded 1200x630 PNG share card for a run result
// GET /api/pixel-agent-share-card?run=RUNID

const satori = require('satori');
const { Resvg } = require('@resvg/resvg-js');
const storage = require('../_utils/companyStorage');
const fs = require('fs');
const path = require('path');

// Load font at cold start
const fontData = fs.readFileSync(path.join(__dirname, 'SpaceGrotesk-Bold.ttf'));

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type'
};

const TIER_COLORS = {
  legendary: '#f59e0b',
  epic: '#8b5cf6',
  rare: '#3b82f6',
  uncommon: '#10b981',
  common: '#9ca3af'
};

module.exports = async function (context, req) {
  if (req.method === 'OPTIONS') {
    context.res = { status: 204, headers: CORS_HEADERS, body: '' };
    return;
  }

  const runId = req.query.run;
  if (!runId) {
    context.res = { status: 400, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' }, body: { error: 'Missing run parameter' } };
    return;
  }

  try {
    const runs = (await storage.getState('pixelAgentRuns')) || [];
    const run = runs.find(r => r.runId === runId);

    if (!run) {
      context.res = { status: 404, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' }, body: { error: 'Run not found' } };
      return;
    }

    // Extract score and verdict from result
    const result = run.result || {};
    const score = result.score ?? result.overall_score ?? null;
    const verdict = result.verdict ?? result.overall_verdict ?? null;
    const accent = TIER_COLORS[run.agentTier] || '#8F00FF';
    const tierLabel = (run.agentTier || 'common').toUpperCase();

    // Build satori markup
    const children = [];

    // Top: agent name + tier badge
    children.push({
      type: 'div',
      props: {
        style: { display: 'flex', alignItems: 'center', gap: 16 },
        children: [
          { type: 'span', props: { style: { fontSize: 48, fontWeight: 700, color: '#E8E8F0' }, children: run.agentName || 'Agent' } },
          { type: 'span', props: { style: { fontSize: 16, fontWeight: 700, color: accent, border: '2px solid ' + accent, borderRadius: 999, padding: '4px 14px' }, children: tierLabel } }
        ]
      }
    });

    // Score + verdict area
    if (score !== null && score !== undefined) {
      const scoreChildren = [
        { type: 'span', props: { style: { fontSize: 120, fontWeight: 700, color: '#8F00FF', lineHeight: 1 }, children: String(Math.round(Number(score))) } },
        { type: 'span', props: { style: { fontSize: 20, color: '#6B6B80', marginTop: 8 }, children: 'out of 100' } }
      ];
      if (verdict) {
        scoreChildren.push({ type: 'span', props: { style: { fontSize: 24, color: '#9090A0', fontStyle: 'italic', marginTop: 24, maxWidth: 600 }, children: '\u201C' + String(verdict).substring(0, 150) + '\u201D' } });
      }
      children.push({
        type: 'div',
        props: {
          style: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', flex: 1, marginTop: 32 },
          children: scoreChildren
        }
      });
    } else if (verdict) {
      children.push({
        type: 'div',
        props: {
          style: { display: 'flex', flex: 1, alignItems: 'center', justifyContent: 'center', marginTop: 40 },
          children: [{ type: 'span', props: { style: { fontSize: 32, color: '#C0C0D0', fontStyle: 'italic', maxWidth: 900, textAlign: 'center' }, children: '\u201C' + String(verdict).substring(0, 200) + '\u201D' } }]
        }
      });
    } else {
      children.push({
        type: 'div',
        props: {
          style: { display: 'flex', flex: 1, alignItems: 'center', justifyContent: 'center' },
          children: [{ type: 'span', props: { style: { fontSize: 28, color: '#6B6B80' }, children: 'Result generated by ' + (run.agentName || 'Pixel Agents') } }]
        }
      });
    }

    // Footer
    children.push({
      type: 'div',
      props: {
        style: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid #1A1A2E', paddingTop: 20 },
        children: [
          { type: 'span', props: { style: { fontSize: 20, color: '#4A4A60', fontWeight: 700 }, children: 'Pixel Agents' } },
          { type: 'span', props: { style: { fontSize: 16, color: '#3A3A50' }, children: 'ambientpixels.ai/pixel-agents' } }
        ]
      }
    });

    const markup = {
      type: 'div',
      props: {
        style: {
          display: 'flex',
          flexDirection: 'column',
          width: 1200,
          height: 630,
          background: '#08080A',
          padding: 60,
          fontFamily: 'Space Grotesk'
        },
        children: children
      }
    };

    const svg = await satori(markup, {
      width: 1200,
      height: 630,
      fonts: [{ name: 'Space Grotesk', data: fontData, weight: 700, style: 'normal' }]
    });

    const resvg = new Resvg(svg, { fitTo: { mode: 'width', value: 1200 } });
    const pngData = resvg.render();
    const pngBuffer = pngData.asPng();

    context.res = {
      status: 200,
      headers: {
        ...CORS_HEADERS,
        'Content-Type': 'image/png',
        'Cache-Control': 'public, max-age=86400'
      },
      body: pngBuffer,
      isRaw: true
    };

  } catch (err) {
    context.log.error('[ShareCard] Error:', err.message, err.stack);
    context.res = {
      status: 500,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      body: { error: 'Failed to generate share card' }
    };
  }
};
