name: Azure Static Web Apps CI/CD - ambientpixelsV2

on:
  push:
    branches: [ "master" ]
  workflow_run:
    workflows: ["Update Nova Memory"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SKY_05CC8E110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: ""
          api_location: ""
          skip_app_build: "true"
