name: Build and deploy Node.js Function App to Azure - ambientpixels-meme-api

on:
  push:
    branches:
      - main  # Matches your repo
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install in meme-api
        working-directory: ./meme-api
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
 
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./meme-api

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./meme-api
 
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Added

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ambientpixels-meme-api'
          slot-name: 'Production'
          package: ./meme-api