name: Azure Static Web Apps CI/CD - ambientpixelsV2
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SKY_05CC8E110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # Root—index.html, projects.html
          output_location: "" # No build—static files
          api_location: "" # No API build—Function App separate
