name: Deploy to Azure Functions (Nova API)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'ambientpixels-api'
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_AMBIENTPIXELS_API }}
          slot-name: 'production'  # ← this line fixes the RBAC error
