name: Deploy Azure Functions

on:
  push:
    branches:
      - master  # Trigger deployment when a commit is pushed to 'master' branch
  pull_request:
    branches:
      - master  # Trigger deployment on PRs to 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: |
        npm install

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ambientpixels-nova-api  # Name of your Azure Function App
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Set this in GitHub Secrets
