# .github/workflows/deploy-ambientpixels-api.yml
name: Deploy to Azure Functions (Nova API via RBAC)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - 'package.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ambientpixels-api
          package: '.'
          slot-name: 'production'
