name: Deploy to Azure Functions
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Add this
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: List Files
      run: ls -R .
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ambientpixels-meme-api-fn
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}