# Deploy Azure Functions to ambientpixels-meme-api-fn
name: Deploy to Azure Functions
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # Required for Deployment Center sync
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4
    - name: List Files
      run: ls -R .  # Debug to confirm api/ deploys
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ambientpixels-meme-api-fn
        package: .
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}