name: Deploy Azure Functions

on:
  push:
    branches:
      - clean-master-nohistory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./meme-api  # Only if package.json exists here

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'ambientpixels-meme-api-f5cdagaqhjb2asfg'
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}