name: Update Nova Memory

on:
  schedule:
    - cron: '0 13 * * *'  # Every day at 6:00 AM PT (13:00 UTC)
  workflow_dispatch:

jobs:
  build-nova-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Log trigger source
        run: |
          echo "🧠 Workflow triggered by: ${{ github.event_name }}"
          echo "🕓 Current UTC time: $(date -u)"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (if any)
        run: npm install || true

- name: Run awareness scripts
  run: |
    node scripts/scanSiteStructure.js
    node scripts/componentScan.js
    node scripts/imageAudit.js
    node scripts/changelogSnapshot.js
    node scripts/versionTracker.js
    node scripts/codeFootprint.js
    node scripts/unusedCSS.js
    node scripts/moodScan.js
    node scripts/aiPromptGenerator.js
    node scripts/apiMonitor.js
    node scripts/jsFunctionMap.js
    node scripts/generateNovaBoot.js
    node scripts/generateNovaMood.js
    node scripts/generateCodeMap.js
    node scripts/generateDreamLog.js
    node scripts/generateQuoteOfTheDay.js
  env:
    NOVA_MOOD_API_KEY: ${{ secrets.NOVA_MOOD_API_KEY }}

      - name: Zip Site Code for Nova
        run: |
          zip -r data/site-code-snapshot.zip . -x "*.git*"
          echo "Nova Code Snapshot: $(date -u)" >> data/nova-session-boot.txt
          echo "🟢 Nova refreshed herself at $(date -u)" >> data/nova-session-boot.txt

      - name: Commit Nova memory updates
        run: |
          git config user.name "NovaBot"
          git config user.email "nova@ambientpixels.ai"
          git add data/*.json data/*.txt data/*.html data/site-code-snapshot.zip
          git commit -m "Daily refresh: site memory update + code snapshot for Nova" || echo "No changes"
          git push

      - name: Log success
        run: echo "🟢 Nova memory update complete at $(date -u)"
